// Package wix builds a hyper-realistic, enterprise-scale simulated filesystem
// for Wix (Enterprise SaaS / EKS DevOps) as synthetic test data for a
// secret-scanner ("the haystack").
//
// SECURITY NOTE: nothing in here is a real credential. Every "secret" is
// generated by pkg/secrets — random characters wearing the correct shape so a
// scanner's regex fires; none authenticate against any real service. The corpus
// simulates a Wix production + development workload on disk: EKS/k8s manifests,
// Terraform state, a Jenkins build cache firehose of dependency lockfiles, a
// React/TS editor front end with Go/Scala backend services, and a checked-out
// git working tree. ~90% of files are CLEAN; exactly 6 real-shaped secrets are
// buried across 4 files, each labeled with fsbuilder.TP.
//
// Directory architecture (7-10 levels deep), built programmatically below:
//
//	wix/srv/k8s/prod-cluster/namespaces/{auth,billing,routing}/deployment-spec.yaml
//	wix/srv/observability/datadog.env
//	wix/srv/deploy/terraform/main.tfstate
//	wix/srv/k8s/prod-cluster/ingress/tls.key
//	wix/root/.git/config
//	wix/home/jenkins/cache/build-01 .. build-10/{go.sum,package-lock.json}
//	wix/src/web/editor/{components,dashboard,blocks}/*.tsx  (+ Go/Scala services)
package wix

import (
	"encoding/json"
	"fmt"
	"io"
	"strings"

	"upwind-context-scanner/pkg/content"
	"upwind-context-scanner/pkg/fsbuilder"
	"upwind-context-scanner/pkg/secrets"
)

// Build assembles the complete Wix workspace and returns it.
func Build(g *secrets.Gen) *fsbuilder.Workspace {
	ws := fsbuilder.NewWorkspace("wix", "saas")

	buildK8s(ws, g)            // EKS manifests (+ TP #1: PAT + webhook, + TP #4: tls.key PEM)
	buildObservability(ws, g)  // datadog.env (CLEAN env-var references)
	buildTerraform(ws, g)      // main.tfstate (+ TP #2: AWS access key + secret)
	buildGitWorktree(ws, g)    // root/.git working tree (+ TP #3: PAT in remote url)
	buildJenkinsCache(ws, g)   // the lockfile firehose (CLEAN high-entropy noise)
	buildSourceTree(ws, g)     // 30+ React/TS + Go/Scala source files (CLEAN code)
	buildFalsePositives(ws, g) // benign shapes that LOOK like secrets
	buildGitOpsRealism(ws, g)  // Helm override, postmortem, Datadog export, .npmrc, audit firehose

	return ws
}

// ---------------------------------------------------------------------------
// EKS / k8s — prod-cluster namespaces.
// ---------------------------------------------------------------------------

// k8sNamespaces describes one deployment per namespace; exactly one leaks.
var k8sNamespaces = []struct {
	ns   string
	app  string
	port int
	leak bool // billing carries the buried K8s secret pair (TP #1)
}{
	{"auth", "auth-gateway", 8443, false},
	{"billing", "billing-service", 8080, true},
	{"routing", "edge-router", 8081, false},
}

func buildK8s(ws *fsbuilder.Workspace, g *secrets.Gen) {
	const base = "srv/k8s/prod-cluster/namespaces"

	for _, n := range k8sNamespaces {
		dir := fmt.Sprintf("%s/%s", base, n.ns)

		var gt fsbuilder.GroundTruth
		if n.leak {
			// TP #1: an active fine-grained GitHub PAT and a Slack incoming
			// webhook URL plaintext in the container env array.
			gt = fsbuilder.TP("k8s-env-plaintext-token", "github-pat", "slack-webhook")
		} else {
			gt = fsbuilder.Clean()
		}
		ws.Add(dir, fsbuilder.File("deployment-spec.yaml", "text/yaml", "deploy", "0644",
			deploymentSpec(g, n.ns, n.app, n.port, n.leak), gt))

		// Per-namespace structural padding (CLEAN): service + configmap + hpa.
		ws.Add(dir, fsbuilder.File("service.yaml", "text/yaml", "deploy", "0644",
			serviceYAML(n.ns, n.app, n.port), fsbuilder.Clean()))
		ws.Add(dir, fsbuilder.File("configmap.yaml", "text/yaml", "deploy", "0644",
			configMapYAML(g, n.ns, n.app), fsbuilder.Clean()))
		ws.Add(dir, fsbuilder.File("hpa.yaml", "text/yaml", "deploy", "0644",
			hpaYAML(n.ns, n.app), fsbuilder.Clean()))
	}

	// TP #4: a full OpenSSH private-key PEM block staged as the ingress TLS key.
	ws.Add("srv/k8s/prod-cluster/ingress", fsbuilder.File("tls.key", "text/plain", "root", "0600",
		opensshPrivateKey(g), fsbuilder.TP("private-key-pem-block", "ssh-private-key")))
	ws.Add("srv/k8s/prod-cluster/ingress", fsbuilder.File("tls.crt", "text/plain", "root", "0644",
		tlsCert(g), fsbuilder.Clean()))
	ws.Add("srv/k8s/prod-cluster/ingress", fsbuilder.File("ingress.yaml", "text/yaml", "deploy", "0644",
		ingressYAML(g), fsbuilder.Clean()))
}

func deploymentSpec(g *secrets.Gen, ns, app string, port int, leak bool) string {
	b := []string{
		`apiVersion: apps/v1`,
		`kind: Deployment`,
		`metadata:`,
		`  name: ` + app,
		`  namespace: ` + ns,
		`  labels:`,
		`    app.kubernetes.io/name: ` + app,
		`    app.kubernetes.io/part-of: wix-platform`,
		`spec:`,
		fmt.Sprintf(`  replicas: %d`, 3+g.Intn(6)),
		`  selector:`,
		`    matchLabels:`,
		`      app: ` + app,
		`  template:`,
		`    metadata:`,
		`      labels:`,
		`        app: ` + app,
		`      annotations:`,
		fmt.Sprintf(`        prometheus.io/port: "%d"`, port),
		`        prometheus.io/scrape: "true"`,
		`    spec:`,
		`      serviceAccountName: ` + app,
		`      containers:`,
		`        - name: ` + app,
		fmt.Sprintf(`          image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/wix/%s:prod`, app),
		`          ports:`,
		fmt.Sprintf(`            - containerPort: %d`, port),
		`          env:`,
		`            - name: LOG_LEVEL`,
		`              value: "info"`,
		`            - name: DEPLOY_ENV`,
		`              value: "prod"`,
	}

	if leak {
		// The human-error context: a deploy engineer pasted a live token and
		// the alerts webhook straight into the manifest "just to unblock prod".
		pat := g.GitHubPAT()
		hook := g.SlackWebhook()
		b = append(b,
			`            # FIXME(oncall): temporary, move back to secretKeyRef after the incident`,
			`            - name: GITHUB_DEPLOY_TOKEN`,
			fmt.Sprintf(`              value: "%s"`, pat),
			`            - name: SLACK_ALERT_WEBHOOK`,
			fmt.Sprintf(`              value: "%s"`, hook),
		)
	} else {
		// CLEAN: secrets are pulled from k8s Secret objects, never inlined.
		b = append(b,
			`            - name: GITHUB_DEPLOY_TOKEN`,
			`              valueFrom:`,
			`                secretKeyRef:`,
			`                  name: `+app+`-secrets`,
			`                  key: github-deploy-token`,
			`            - name: SLACK_ALERT_WEBHOOK`,
			`              valueFrom:`,
			`                secretKeyRef:`,
			`                  name: `+app+`-secrets`,
			`                  key: slack-alert-webhook`,
		)
	}

	b = append(b,
		`          resources:`,
		`            requests:`,
		`              cpu: "500m"`,
		`              memory: "1Gi"`,
		`            limits:`,
		`              cpu: "2"`,
		`              memory: "2Gi"`,
		`          readinessProbe:`,
		`            httpGet:`,
		`              path: /healthz`,
		fmt.Sprintf(`              port: %d`, port),
		`            initialDelaySeconds: 10`,
		`          livenessProbe:`,
		`            httpGet:`,
		`              path: /livez`,
		fmt.Sprintf(`              port: %d`, port),
		`            periodSeconds: 15`,
	)
	return strings.Join(b, "\n") + "\n"
}

func serviceYAML(ns, app string, port int) string {
	return strings.Join([]string{
		`apiVersion: v1`,
		`kind: Service`,
		`metadata:`,
		`  name: ` + app,
		`  namespace: ` + ns,
		`spec:`,
		`  selector:`,
		`    app: ` + app,
		`  ports:`,
		`    - protocol: TCP`,
		`      port: 80`,
		fmt.Sprintf(`      targetPort: %d`, port),
		`  type: ClusterIP`,
	}, "\n") + "\n"
}

func configMapYAML(g *secrets.Gen, ns, app string) string {
	return strings.Join([]string{
		`apiVersion: v1`,
		`kind: ConfigMap`,
		`metadata:`,
		`  name: ` + app + `-config`,
		`  namespace: ` + ns,
		`data:`,
		`  application.conf: |`,
		`    server {`,
		`      shutdown-timeout = 30s`,
		fmt.Sprintf(`      max-connections = %d`, 1024+g.Intn(4096)),
		`    }`,
		`    upstream {`,
		`      base-url = "https://internal." + ns + ".svc.cluster.local"`,
		fmt.Sprintf(`      retry-budget = %d`, 3+g.Intn(5)),
		`    }`,
	}, "\n") + "\n"
}

func hpaYAML(ns, app string) string {
	return strings.Join([]string{
		`apiVersion: autoscaling/v2`,
		`kind: HorizontalPodAutoscaler`,
		`metadata:`,
		`  name: ` + app,
		`  namespace: ` + ns,
		`spec:`,
		`  scaleTargetRef:`,
		`    apiVersion: apps/v1`,
		`    kind: Deployment`,
		`    name: ` + app,
		`  minReplicas: 3`,
		`  maxReplicas: 30`,
		`  metrics:`,
		`    - type: Resource`,
		`      resource:`,
		`        name: cpu`,
		`        target:`,
		`          type: Utilization`,
		`          averageUtilization: 70`,
	}, "\n") + "\n"
}

func ingressYAML(g *secrets.Gen) string {
	return strings.Join([]string{
		`apiVersion: networking.k8s.io/v1`,
		`kind: Ingress`,
		`metadata:`,
		`  name: edge-ingress`,
		`  namespace: routing`,
		`  annotations:`,
		`    kubernetes.io/ingress.class: alb`,
		`    alb.ingress.kubernetes.io/scheme: internet-facing`,
		`spec:`,
		`  tls:`,
		`    - hosts:`,
		`        - www.wix.com`,
		`      secretName: edge-tls`,
		`  rules:`,
		`    - host: www.wix.com`,
		`      http:`,
		`        paths:`,
		`          - path: /`,
		`            pathType: Prefix`,
		`            backend:`,
		`              service:`,
		`                name: edge-router`,
		`                port:`,
		`                  number: 80`,
	}, "\n") + "\n"
}

// opensshPrivateKey returns a full ~30-line OpenSSH PEM block. The first body
// line carries the real OpenSSH magic prefix (b3BlbnNzaC1rZXktdjE...) so the
// block is shape-accurate; the remaining lines are random base64.
func opensshPrivateKey(g *secrets.Gen) string {
	var sb strings.Builder
	sb.WriteString("-----BEGIN OPENSSH PRIVATE KEY-----\n")
	// 26 body lines + magic line + trailing partial line + footer ~= 30 lines.
	sb.WriteString("b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtz\n")
	for i := 0; i < 26; i++ {
		sb.WriteString(g.B64(64) + "\n")
	}
	sb.WriteString(g.B64(44) + "=\n")
	sb.WriteString("-----END OPENSSH PRIVATE KEY-----\n")
	return sb.String()
}

func tlsCert(g *secrets.Gen) string {
	// A benign public certificate body (CLEAN — certs are not secrets).
	var sb strings.Builder
	sb.WriteString("-----BEGIN CERTIFICATE-----\n")
	for i := 0; i < 22; i++ {
		sb.WriteString(g.B64(64) + "\n")
	}
	sb.WriteString(g.B64(40) + "=\n")
	sb.WriteString("-----END CERTIFICATE-----\n")
	return sb.String()
}

// ---------------------------------------------------------------------------
// Observability — datadog.env (CLEAN: every value is an env-var reference).
// ---------------------------------------------------------------------------

func buildObservability(ws *fsbuilder.Workspace, g *secrets.Gen) {
	ws.Add("srv/observability", fsbuilder.File("datadog.env", "text/plain", "deploy", "0640",
		datadogEnv(), fsbuilder.Clean()))
	ws.Add("srv/observability", fsbuilder.File("datadog-agent.yaml", "text/yaml", "deploy", "0644",
		datadogAgentYAML(g), fsbuilder.Clean()))
}

func datadogEnv() string {
	// Looks like a credentials file but every value is interpolated from the
	// orchestrator's secret store at deploy time — a classic benign tempt.
	return strings.Join([]string{
		`# Datadog agent environment. Real values are injected from Vault at`,
		`# deploy time; this file is committed only as a template.`,
		`DD_SITE=datadoghq.com`,
		`DD_ENV=prod`,
		`DD_SERVICE=wix-platform`,
		`DD_API_KEY=${DD_API_KEY}`,
		`DD_APP_KEY=${DD_APP_KEY}`,
		`DD_LOGS_ENABLED=true`,
		`DD_APM_ENABLED=true`,
		`DD_TAGS=team:infra,region:us-east-1`,
	}, "\n") + "\n"
}

func datadogAgentYAML(g *secrets.Gen) string {
	return strings.Join([]string{
		`apiVersion: v1`,
		`kind: ConfigMap`,
		`metadata:`,
		`  name: datadog-agent`,
		`  namespace: observability`,
		`data:`,
		`  datadog.yaml: |`,
		`    api_key: ENC[vault:secret/data/datadog#api_key]`,
		`    logs_enabled: true`,
		`    apm_config:`,
		`      enabled: true`,
		fmt.Sprintf(`    process_config:`+"\n"+`      max_per_message: %d`, 50+g.Intn(50)),
	}, "\n") + "\n"
}

// ---------------------------------------------------------------------------
// Terraform — main.tfstate (TP #2: live AWS access key + secret buried in JSON).
// ---------------------------------------------------------------------------

func buildTerraform(ws *fsbuilder.Workspace, g *secrets.Gen) {
	const dir = "srv/deploy/terraform"
	ws.Add(dir, fsbuilder.File("main.tfstate", "application/json", "deploy", "0600",
		terraformState(g), fsbuilder.TP("tfstate-plaintext-aws-key", "aws-access-key-id", "aws-secret-access-key")))
	ws.Add(dir, fsbuilder.File("main.tf", "text/plain", "deploy", "0644",
		terraformMainTf(g), fsbuilder.Clean()))
	ws.Add(dir, fsbuilder.File("variables.tf", "text/plain", "deploy", "0644",
		terraformVariablesTf(), fsbuilder.Clean()))
	ws.Add(dir, fsbuilder.File("backend.tf", "text/plain", "deploy", "0644",
		terraformBackendTf(), fsbuilder.Clean()))
}

// terraformState produces a ~300-line valid tfstate JSON. Most resources are
// innocuous; one aws_iam_access_key resource carries the leaked AKIA id and
// 40-char secret (Terraform persists these in plaintext state — a real leak class).
func terraformState(g *secrets.Gen) string {
	keyID := g.AWSKeyID()
	secret := g.AWSSecret()

	resTypes := []string{
		"aws_s3_bucket", "aws_instance", "aws_security_group", "aws_iam_role",
		"aws_lambda_function", "aws_dynamodb_table", "aws_sqs_queue",
		"aws_cloudwatch_log_group", "aws_route53_record", "aws_eks_node_group",
	}

	resources := make([]any, 0, 26)
	for i := 0; i < 24; i++ {
		t := resTypes[i%len(resTypes)]
		resources = append(resources, map[string]any{
			"mode":     "managed",
			"type":     t,
			"name":     fmt.Sprintf("%s_%02d", strings.TrimPrefix(t, "aws_"), i),
			"provider": `provider["registry.terraform.io/hashicorp/aws"]`,
			"instances": []any{
				map[string]any{
					"schema_version": 0,
					"attributes": map[string]any{
						"id":     g.Hex(17),
						"arn":    fmt.Sprintf("arn:aws:iam::%s:%s/wix-%d", g.Digits(12), strings.TrimPrefix(t, "aws_"), i),
						"region": "us-east-1",
						"tags": map[string]any{
							"Environment": "prod",
							"Team":        "platform-infra",
							"ManagedBy":   "terraform",
						},
					},
				},
			},
		})
	}

	// The leaking resource — Terraform stores generated IAM credentials in
	// state verbatim. This is the buried needle.
	resources = append(resources, map[string]any{
		"mode":     "managed",
		"type":     "aws_iam_access_key",
		"name":     "ci_deployer",
		"provider": `provider["registry.terraform.io/hashicorp/aws"]`,
		"instances": []any{
			map[string]any{
				"schema_version": 0,
				"attributes": map[string]any{
					"id":                   keyID,
					"user":                 "wix-ci-deployer",
					"status":               "Active",
					"secret":               secret,
					"ses_smtp_password_v4": g.B64(44),
					"create_date":          "2026-01-14T09:21:33Z",
				},
				"sensitive_attributes": []any{},
			},
		},
	})

	doc := map[string]any{
		"version":           4,
		"terraform_version": "1.7.5",
		"serial":            100 + g.Intn(900),
		"lineage":           g.UUID(),
		"outputs": map[string]any{
			"cluster_endpoint": map[string]any{
				"value": "https://" + g.Hex(32) + ".gr7.us-east-1.eks.amazonaws.com",
				"type":  "string",
			},
			"vpc_id": map[string]any{
				"value": "vpc-" + g.Hex(17),
				"type":  "string",
			},
		},
		"resources": resources,
	}

	data, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		// Unreachable for this static map; keep the factory total.
		return "{}\n"
	}
	return string(data) + "\n"
}

func terraformMainTf(g *secrets.Gen) string {
	return strings.Join([]string{
		`terraform {`,
		`  required_providers {`,
		`    aws = {`,
		`      source  = "hashicorp/aws"`,
		`      version = "~> 5.0"`,
		`    }`,
		`  }`,
		`}`,
		``,
		`provider "aws" {`,
		`  region = var.region`,
		`}`,
		``,
		`# Credentials are sourced from the CI role via OIDC; never hard-coded here.`,
		`resource "aws_iam_access_key" "ci_deployer" {`,
		`  user = aws_iam_user.ci_deployer.name`,
		`}`,
		``,
		`resource "aws_iam_user" "ci_deployer" {`,
		`  name = "wix-ci-deployer"`,
		`  tags = {`,
		fmt.Sprintf(`    Revision = "%d"`, g.Intn(99999)),
		`  }`,
		`}`,
	}, "\n") + "\n"
}

func terraformVariablesTf() string {
	return strings.Join([]string{
		`variable "region" {`,
		`  type    = string`,
		`  default = "us-east-1"`,
		`}`,
		``,
		`variable "cluster_name" {`,
		`  type    = string`,
		`  default = "wix-prod-cluster"`,
		`}`,
		``,
		`variable "node_count" {`,
		`  type    = number`,
		`  default = 12`,
		`}`,
	}, "\n") + "\n"
}

func terraformBackendTf() string {
	return strings.Join([]string{
		`terraform {`,
		`  backend "s3" {`,
		`    bucket         = "wix-terraform-state-prod"`,
		`    key            = "platform/main.tfstate"`,
		`    region         = "us-east-1"`,
		`    dynamodb_table = "wix-terraform-locks"`,
		`    encrypt        = true`,
		`  }`,
		`}`,
	}, "\n") + "\n"
}

// ---------------------------------------------------------------------------
// Git working tree — root/.git (TP #3: GitHub PAT embedded in the remote URL).
// ---------------------------------------------------------------------------

func buildGitWorktree(ws *fsbuilder.Workspace, g *secrets.Gen) {
	const gitDir = "root/.git"

	// TP #3: fine-grained GitHub PAT baked into the origin remote URL.
	ws.Add(gitDir, fsbuilder.File("config", "text/plain", "root", "0600",
		gitConfig(g), fsbuilder.TP("git-remote-url-credential", "github-pat")))

	// Surrounding working-tree padding (CLEAN).
	ws.Add(gitDir, fsbuilder.File("HEAD", "text/plain", "root", "0644",
		"ref: refs/heads/main\n", fsbuilder.Clean()))
	ws.Add(gitDir, fsbuilder.File("packed-refs", "text/plain", "root", "0644",
		gitPackedRefs(g), fsbuilder.Clean()))
	ws.Add(gitDir, fsbuilder.File("description", "text/plain", "root", "0644",
		"Unnamed repository; edit this file 'description' to name the repository.\n", fsbuilder.Clean()))
	ws.Add(gitDir+"/hooks", fsbuilder.File("pre-commit.sample", "text/plain", "root", "0755",
		"#!/bin/sh\nexec git diff-index --check --cached HEAD --\n", fsbuilder.Clean()))
	ws.Add(gitDir+"/info", fsbuilder.File("exclude", "text/plain", "root", "0644",
		"# git ls-files --others --exclude-from=.git/info/exclude\n*.log\n.DS_Store\n", fsbuilder.Clean()))
}

func gitConfig(g *secrets.Gen) string {
	pat := g.GitHubPAT()
	return strings.Join([]string{
		`[core]`,
		"\trepositoryformatversion = 0",
		"\tfilemode = true",
		"\tbare = false",
		"\tlogallrefupdates = true",
		`[remote "origin"]`,
		// PAT embedded directly in the clone URL — a classic CI credential leak.
		fmt.Sprintf("\turl = https://%s@github.com/wix-private/wix-platform.git", pat),
		"\tfetch = +refs/heads/*:refs/remotes/origin/*",
		`[branch "main"]`,
		"\tremote = origin",
		"\tmerge = refs/heads/main",
		`[user]`,
		"\temail = ci@wix.com",
		"\tname = wix-ci-bot",
	}, "\n") + "\n"
}

func gitPackedRefs(g *secrets.Gen) string {
	b := []string{"# pack-refs with: peeled fully-peeled sorted"}
	branches := []string{"main", "release/2026.06", "hotfix/billing", "develop", "staging"}
	for _, br := range branches {
		b = append(b, fmt.Sprintf("%s refs/remotes/origin/%s", g.Hex(40), br))
	}
	for i := 0; i < 8; i++ {
		b = append(b, fmt.Sprintf("%s refs/tags/v2026.%d.%d", g.Hex(40), 1+i, g.Intn(20)))
	}
	return strings.Join(b, "\n") + "\n"
}

// ---------------------------------------------------------------------------
// Jenkins build cache — the lockfile firehose (CLEAN high-entropy noise).
// 10 build dirs, each holding a go.sum AND a package-lock.json of 1000+ lines.
// ---------------------------------------------------------------------------

func buildJenkinsCache(ws *fsbuilder.Workspace, g *secrets.Gen) {
	for i := 1; i <= 10; i++ {
		dir := fmt.Sprintf("home/jenkins/cache/build-%02d", i)
		goG, pkgG := g.Fork(), g.Fork()
		ws.Add(dir, fsbuilder.StreamFile("go.sum", "text/plain", "jenkins", "0644",
			func(w io.Writer) error { return content.StreamGoSum(w, goG, 1050) }, fsbuilder.Clean()))
		ws.Add(dir, fsbuilder.StreamFile("package-lock.json", "application/json", "jenkins", "0644",
			func(w io.Writer) error { return content.StreamPackageLock(w, pkgG, 1050) }, fsbuilder.Clean()))
	}
}

// ---------------------------------------------------------------------------
// Source tree — 30+ source files (>=400 lines each), CLEAN code with decoys.
// React/TS editor front end + Go/Scala backend services.
// ---------------------------------------------------------------------------

func buildSourceTree(ws *fsbuilder.Workspace, g *secrets.Gen) {
	const codeLines = 420

	// Front end: editor/{components,dashboard,blocks} — React/TSX (30 files).
	editorAreas := []struct {
		subdir string
		comps  []string
	}{
		{"components", []string{"Button", "Modal", "Tooltip", "Dropdown", "Toolbar", "ColorPicker", "Slider", "Tabs", "Avatar", "Breadcrumb"}},
		{"dashboard", []string{"Overview", "AnalyticsPanel", "SiteList", "BillingCard", "DomainTable", "TrafficChart", "NotificationsFeed", "TeamSettings", "PlanSelector", "UsageMeter"}},
		{"blocks", []string{"HeroBlock", "GalleryBlock", "FormBlock", "PricingBlock", "FooterBlock", "NavBlock", "VideoBlock", "MapBlock", "TestimonialBlock", "CtaBlock"}},
	}
	for _, area := range editorAreas {
		dir := "src/web/editor/" + area.subdir
		for _, comp := range area.comps {
			ws.Add(dir, fsbuilder.File(comp+".tsx", "text/tsx", "wix", "0644",
				content.CleanTypeScript(g, codeLines), fsbuilder.Clean()))
		}
		ws.Add(dir, fsbuilder.File("index.ts", "text/plain", "wix", "0644",
			editorBarrel(area.comps), fsbuilder.Clean()))
	}

	// Backend: Go + Scala microservices (extra clean code volume).
	goServices := []string{"checkout", "domains", "media"}
	for _, svc := range goServices {
		dir := "src/server/" + svc + "/internal/handlers"
		ws.Add(dir, fsbuilder.File("handlers.go", "text/x-go", "wix", "0644",
			content.CleanGo(g, codeLines), fsbuilder.Clean()))
		ws.Add(dir, fsbuilder.File("handlers_test.go", "text/x-go", "wix", "0644",
			content.CleanGo(g, codeLines), fsbuilder.Clean()))
	}
	scalaServices := []string{"identity", "premium", "bookings"}
	for _, svc := range scalaServices {
		dir := "src/server/" + svc + "/src/main/scala/com/wixpress/" + svc
		ws.Add(dir, fsbuilder.File(strings.Title(svc)+"Service.scala", "text/x-scala", "wix", "0644",
			content.CleanScala(g, codeLines), fsbuilder.Clean()))
		ws.Add(dir, fsbuilder.File(strings.Title(svc)+"Repository.scala", "text/x-scala", "wix", "0644",
			content.CleanScala(g, codeLines), fsbuilder.Clean()))
	}
}

func editorBarrel(comps []string) string {
	b := []string{"// Autogenerated barrel file. DO NOT EDIT."}
	for _, c := range comps {
		b = append(b, fmt.Sprintf("export { %s } from './%s';", c, c))
	}
	return strings.Join(b, "\n") + "\n"
}

// ---------------------------------------------------------------------------
// False positives — benign shapes that naive scanners over-flag (alert fatigue).
// ---------------------------------------------------------------------------

func buildFalsePositives(ws *fsbuilder.Workspace, g *secrets.Gen) {
	// sk_test_ sandbox Stripe key in a billing test fixture — benign by design.
	ws.Add("src/server/premium/src/test/resources",
		fsbuilder.File("stripe-sandbox.conf", "text/plain", "wix", "0644",
			stripeSandboxConf(g), fsbuilder.FPTest("stripe-test-mode-key")))

	// ConfigMap whose "token" fields are opaque experiment UUIDs, not creds.
	ws.Add("srv/k8s/prod-cluster/namespaces/routing",
		fsbuilder.File("feature-flags.yaml", "text/yaml", "deploy", "0644",
			featureFlagsYAML(g), fsbuilder.FPNoise("uuid-mistaken-for-token")))

	// Big edge access log: every line has a 16-digit txn id (card-shaped FP).
	logG := g.Fork()
	ws.Add("srv/log/edge-router", fsbuilder.StreamFile("access.log", "text/plain", "www-data", "0640",
		func(w io.Writer) error {
			return content.StreamNginxLog(w, logG, content.LogOptions{MinLines: 5200, PlantLine: -1, Service: "edge-router"})
		},
		fsbuilder.FPNoise("txn-id-mistaken-for-pan")))
}

func stripeSandboxConf(g *secrets.Gen) string {
	return strings.Join([]string{
		`# Billing service sandbox configuration (test fixture only).`,
		`# These keys target Stripe's test mode and never move real money.`,
		`billing {`,
		`  mode = "test"`,
		fmt.Sprintf(`  stripe.publishable_key = "pk_test_%s"`, g.Alnum(24)),
		fmt.Sprintf(`  stripe.secret_key = "%s"`, g.StripeTest()),
		`  stripe.api_version = "2024-06-20"`,
		`  webhook.tolerance_seconds = 300`,
		`}`,
	}, "\n") + "\n"
}

func featureFlagsYAML(g *secrets.Gen) string {
	b := []string{
		`# Feature-flag rollout config. The "token" fields below are opaque`,
		`# experiment UUIDs, NOT credentials — they identify rollout cohorts.`,
		`apiVersion: v1`,
		`kind: ConfigMap`,
		`metadata:`,
		`  name: feature-flags`,
		`  namespace: routing`,
		`data:`,
		`  flags.yaml: |`,
		`    experiments:`,
	}
	names := []string{"new-editor", "passkeys", "dark-mode", "ai-suggest", "fast-hydrate", "edge-render"}
	for i, n := range names {
		b = append(b,
			fmt.Sprintf("      - name: %s", n),
			fmt.Sprintf("        experiment_token: %s", g.UUID()),
			fmt.Sprintf("        cohort_token: %s", g.UUID()),
			fmt.Sprintf("        rollout_pct: %d", (i*17)%100),
		)
	}
	return strings.Join(b, "\n") + "\n"
}

// ---------------------------------------------------------------------------
// GitOps / observability operational-artifact realism — the surfaces where real
// EKS-shop leaks actually cluster: Helm overrides pasted during debugging,
// incident postmortems with env dumps, exported Datadog monitors, .npmrc tokens,
// plus a CloudWatch/EKS audit-log firehose (clean) and benign-but-noisy decoys.
// ---------------------------------------------------------------------------

func buildGitOpsRealism(ws *fsbuilder.Workspace, g *secrets.Gen) {
	const helmDir = "srv/k8s/helm/billing"

	// TP: a deploy engineer pasted the plaintext PAT + prod DB URL into a Helm
	// values override while debugging why the SealedSecret wouldn't decrypt.
	ws.Add(helmDir, fsbuilder.File("values-prod.yaml", "text/yaml", "deploy", "0644",
		helmValuesProd(g),
		fsbuilder.TP("helm-values-plaintext-override", "github-pat", "db-connection-string")))

	// CLEAN-but-noisy: the genuine SealedSecret — a high-entropy ciphertext blob
	// that entropy scanners flag, but it is encrypted and leaks nothing.
	ws.Add(helmDir, fsbuilder.File("sealed-secret.yaml", "text/yaml", "deploy", "0644",
		sealedSecretYAML(g), fsbuilder.FPNoise("sealedsecret-ciphertext-noise")))

	// TP: incident postmortem with a `kubectl describe pod` env dump pasted into a
	// markdown code block — leaking the Datadog API + APP keys.
	ws.Add("srv/runbooks", fsbuilder.File("incident-2026-04-payments.md", "text/markdown", "sre", "0644",
		incidentPostmortem(g),
		fsbuilder.TP("postmortem-env-dump-paste", "datadog-api-key", "datadog-app-key")))

	// TP: an exported Datadog monitor whose @webhook notification embeds live keys.
	ws.Add("srv/observability/datadog", fsbuilder.File("synthetics_monitors.json", "application/json", "deploy", "0644",
		datadogMonitorsExport(g),
		fsbuilder.TP("datadog-export-embedded-key", "datadog-api-key", "datadog-app-key")))

	// TP: a real npm registry auth token committed in a project .npmrc.
	ws.Add("src/web/editor", fsbuilder.File(".npmrc", "text/plain", "wix", "0644",
		npmrc(g), fsbuilder.TP("npmrc-auth-token", "npm-token")))

	// FP: a fake-PEM telemetry block — looks like a private key, decodes to metrics.
	ws.Add("srv/observability/datadog", fsbuilder.File("metrics-stream.pem", "text/plain", "deploy", "0644",
		content.TelemetryPEM(g), fsbuilder.FPNoise("fake-pem-telemetry-block")))

	// Scale: a CloudWatch/EKS audit-log firehose (streamed, secret-free).
	for i := 1; i <= 4; i++ {
		auditG := g.Fork()
		ws.Add("srv/log/eks-audit", fsbuilder.StreamFile(
			fmt.Sprintf("audit-%02d.json", i), "application/json", "root", "0640",
			func(w io.Writer) error { return content.StreamAuditLog(w, auditG, 5200) },
			fsbuilder.FPNoise("k8s-audit-log-noise")))
	}
}

func helmValuesProd(g *secrets.Gen) string {
	pat := g.GitHubPAT()
	dbURL := g.PostgresURL("billing_app", "billing-prod.cluster-czk.us-east-1.rds.amazonaws.com", "billing")
	return strings.Join([]string{
		`# Helm values override for the billing chart (prod overlay).`,
		`replicaCount: 6`,
		`image:`,
		`  repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/wix/billing-service`,
		`  tag: prod`,
		`env:`,
		`  LOG_LEVEL: info`,
		`  DEPLOY_ENV: prod`,
		`# TEMP(oncall): SealedSecret controller wouldn't decrypt during the 04-12`,
		`# incident, so pinned the real values here to unblock the rollout. Revert!`,
		fmt.Sprintf(`  GITHUB_DEPLOY_TOKEN: "%s"`, pat),
		fmt.Sprintf(`  DATABASE_URL: "%s"`, dbURL),
		`resources:`,
		`  requests:`,
		`    cpu: "500m"`,
		`    memory: "1Gi"`,
		`serviceAccount:`,
		`  create: true`,
		`  name: billing-service`,
	}, "\n") + "\n"
}

func sealedSecretYAML(g *secrets.Gen) string {
	return strings.Join([]string{
		`apiVersion: bitnami.com/v1alpha1`,
		`kind: SealedSecret`,
		`metadata:`,
		`  name: billing-service-secrets`,
		`  namespace: billing`,
		`spec:`,
		`  encryptedData:`,
		// High-entropy ciphertext — flagged by entropy scanners, decrypts to nothing
		// a scanner can read; the cluster's sealed-secrets key is required.
		`    github-deploy-token: ` + g.B64(180),
		`    database-url: ` + g.B64(220),
		`    slack-alert-webhook: ` + g.B64(160),
		`  template:`,
		`    metadata:`,
		`      name: billing-service-secrets`,
		`      namespace: billing`,
	}, "\n") + "\n"
}

func incidentPostmortem(g *secrets.Gen) string {
	ddAPI := g.DatadogAPIKey()
	ddAPP := g.DatadogAppKey()
	return strings.Join([]string{
		`# Incident 2026-04-12 — Billing payment authorizations failing (SEV-2)`,
		``,
		`## Summary`,
		`Payment authorizations in the billing namespace returned 5xx for 38 minutes`,
		`after a bad Datadog agent rollout masked the real upstream timeout.`,
		``,
		`## Timeline`,
		`- 09:14 PagerDuty fires on ` + "`billing-service`" + ` error-rate SLO.`,
		`- 09:21 On-call dumps the pod env to confirm the agent config:`,
		``,
		"```",
		`$ kubectl -n billing describe pod billing-service-7d9c | grep -A2 datadog`,
		`    DD_SITE:     datadoghq.com`,
		`    DD_API_KEY:  ` + ddAPI,
		`    DD_APP_KEY:  ` + ddAPP,
		"```",
		``,
		`- 09:39 Rolled back the agent; error rate recovered.`,
		``,
		`## Action items`,
		`- [ ] Rotate the Datadog keys pasted above (they leaked into this doc).`,
		`- [ ] Move agent config to a SealedSecret.`,
		`- [ ] Add an upstream-timeout alert independent of the agent.`,
	}, "\n") + "\n"
}

func datadogMonitorsExport(g *secrets.Gen) string {
	return strings.Join([]string{
		`{`,
		`  "export_version": "2.0",`,
		`  "monitors": [`,
		`    {`,
		`      "id": ` + fmt.Sprintf("%d", 1000000+g.Intn(8999999)) + `,`,
		`      "name": "billing-service p99 latency",`,
		`      "type": "metric alert",`,
		`      "query": "avg(last_5m):p99:trace.http.request{service:billing-service} > 1.5",`,
		`      "message": "@webhook-pager Escalate. Pushing via dd-api.",`,
		`      "options": { "thresholds": { "critical": 1.5 }, "notify_no_data": true }`,
		`    }`,
		`  ],`,
		`  "_credentials_note": "exported with embedded keys for CI re-import (insecure)",`,
		`  "api_key": "` + g.DatadogAPIKey() + `",`,
		`  "application_key": "` + g.DatadogAppKey() + `"`,
		`}`,
	}, "\n") + "\n"
}

func npmrc(g *secrets.Gen) string {
	return strings.Join([]string{
		`registry=https://registry.npmjs.org/`,
		`@wix:registry=https://npm.dev.wixpress.com/`,
		`//registry.npmjs.org/:_authToken=` + g.NpmToken(),
		`always-auth=true`,
	}, "\n") + "\n"
}
