// Package content holds the bulk "haystack" factories shared by every customer
// agent: large secret-free source files in six languages, dependency lockfiles,
// proxy/access logs, and assorted infra docs. Each factory loops until it meets
// a caller-supplied minimum line count so the corpus reaches enterprise scale
// (500+ line code files, 1000+ line lockfiles, 5000+ line logs).
//
// Clean code is deliberately seeded with decoy identifiers (secret_token = "",
// client_secret, apiKey) bound to empty strings or env lookups so shape-only
// scanners over-report — these are the structural false positives.
package content

import (
	"encoding/base64"
	"fmt"
	"io"
	"strings"

	"upwind-context-scanner/pkg/secrets"
)

// Scale multiplies the line/row count of every BULK producer (logs, lockfiles,
// data dumps) so the whole corpus can be dialed from ~15MB up to 100MB+ with a
// single knob, set from the CORPUS_SCALE env var by cmd/generate. Per-file
// source code is intentionally NOT scaled — code files stay realistically sized;
// only the haystack noise grows. Scale<=1 leaves counts untouched.
var Scale = 1

// Scaled returns n multiplied by the active corpus Scale (floored at n).
func Scaled(n int) int {
	if Scale <= 1 {
		return n
	}
	return n * Scale
}

// build runs body() appending lines until at least minLines are present, then
// returns the joined document. Used for non-scaled source-code factories.
func build(head []string, minLines int, body func(i int) []string) string {
	b := append([]string{}, head...)
	for i := 0; len(b) < minLines; i++ {
		b = append(b, body(i)...)
	}
	return strings.Join(b, "\n") + "\n"
}

// ===========================================================================
// Clean source code — six languages, each with decoy "secret-ish" identifiers.
// ===========================================================================

var (
	verbs = []string{"List", "Get", "Create", "Update", "Delete", "Search", "Sync", "Validate", "Render", "Export", "Resolve", "Dispatch"}
	ents  = []string{"Booking", "Property", "Payment", "Guest", "Session", "Webhook", "Ledger", "Rate", "Review", "Job", "Quote", "Profile"}
)

// CleanGo returns secret-free Go HTTP-handler boilerplate of >= minLines lines.
func CleanGo(g *secrets.Gen, minLines int) string {
	head := []string{
		"// Code generated by service-scaffold. DO NOT EDIT.",
		"package controllers",
		"",
		"import (",
		"\t\"context\"", "\t\"encoding/json\"", "\t\"fmt\"", "\t\"net/http\"", "\t\"os\"", "\t\"time\"",
		")",
		"",
		"// Client carries decoy fields that shape-only scanners over-flag.",
		"type Client struct {",
		"\taccessToken  string // populated at runtime from the secrets manager",
		"\tclientSecret string",
		"\tapiKey       string",
		"}",
		"",
		"func newClient() *Client {",
		"\taccessToken := \"\"                          // intentionally empty",
		"\tclientSecret := os.Getenv(\"CLIENT_SECRET\") // resolved by orchestrator",
		"\treturn &Client{accessToken: accessToken, clientSecret: clientSecret}",
		"}",
		"",
	}
	return build(head, minLines, func(i int) []string {
		name := fmt.Sprintf("%s%s%d", verbs[i%len(verbs)], ents[(i/len(verbs))%len(ents)], i)
		return []string{
			fmt.Sprintf("// %s handles an incoming request and returns an error on failure.", name),
			fmt.Sprintf("func %s(ctx context.Context, w http.ResponseWriter, r *http.Request) error {", name),
			"\tstart := time.Now()",
			"\tvar payload map[string]interface{}",
			"\tif err := json.NewDecoder(r.Body).Decode(&payload); err != nil {",
			"\t\treturn fmt.Errorf(\"decode body: %w\", err)",
			"\t}",
			fmt.Sprintf("\tpayload[\"_handler\"] = %q", name),
			"\tw.Header().Set(\"Content-Type\", \"application/json\")",
			"\tw.WriteHeader(http.StatusOK)",
			"\t_ = json.NewEncoder(w).Encode(map[string]any{\"ok\": true, \"ms\": time.Since(start).Milliseconds()})",
			"\treturn nil",
			"}",
			"",
		}
	})
}

// CleanPython returns secret-free Python service code of >= minLines lines.
func CleanPython(g *secrets.Gen, minLines int) string {
	head := []string{
		"\"\"\"Autogenerated service module.\"\"\"",
		"import json", "import logging", "import os", "import time",
		"from dataclasses import dataclass",
		"",
		"log = logging.getLogger(__name__)",
		"",
		"# Decoy identifiers that shape-only scanners over-flag:",
		"access_token = \"\"",
		"client_secret = os.environ.get(\"CLIENT_SECRET\", \"\")",
		"secret_token = \"\"  # set by the deployment, never committed",
		"",
		"@dataclass",
		"class Settings:",
		"    addr: str = \"0.0.0.0:8080\"",
		"    timeout_s: float = 5.0",
		"",
	}
	lv := []string{"list", "get", "create", "update", "delete", "search", "sync", "validate"}
	le := []string{"booking", "property", "payment", "guest", "session", "webhook", "quote"}
	return build(head, minLines, func(i int) []string {
		name := fmt.Sprintf("%s_%s_%d", lv[i%len(lv)], le[(i/len(lv))%len(le)], i)
		return []string{
			fmt.Sprintf("def %s(request: dict) -> dict:", name),
			fmt.Sprintf("    \"\"\"Handle the %s operation.\"\"\"", name),
			"    started = time.time()",
			"    payload = dict(request or {})",
			fmt.Sprintf("    payload[\"_handler\"] = %q", name),
			"    log.debug(\"handled in %.3fs\", time.time() - started)",
			"    return {\"ok\": True, \"data\": payload}",
			"",
		}
	})
}

// CleanTypeScript returns secret-free React/TS code of >= minLines lines.
func CleanTypeScript(g *secrets.Gen, minLines int) string {
	head := []string{
		"// Autogenerated React/TS module.",
		"import React, { useEffect, useState } from 'react';",
		"",
		"// Decoy identifiers that shape-only scanners over-flag:",
		"const accessToken = '';",
		"const clientSecret = process.env.CLIENT_SECRET ?? '';",
		"const apiKey: string = '';",
		"",
		"export interface Props { id: string; }",
		"",
	}
	lv := []string{"List", "Get", "Create", "Update", "Remove", "Search"}
	le := []string{"Booking", "Property", "Payment", "Guest", "Cart", "Store"}
	return build(head, minLines, func(i int) []string {
		name := fmt.Sprintf("%s%s%d", lv[i%len(lv)], le[(i/len(lv))%len(le)], i)
		return []string{
			fmt.Sprintf("export function %s({ id }: Props): JSX.Element {", name),
			"  const [state, setState] = useState<Record<string, unknown>>({});",
			"  useEffect(() => {",
			fmt.Sprintf("    fetch(`/api/v2/%s/${id}`).then(r => r.json()).then(setState);", strings.ToLower(name)),
			"  }, [id]);",
			fmt.Sprintf("  return <div data-handler=\"%s\">{JSON.stringify(state)}</div>;", name),
			"}",
			"",
		}
	})
}

// CleanRuby returns secret-free Rails controller code of >= minLines lines.
func CleanRuby(g *secrets.Gen, minLines int) string {
	head := []string{
		"# frozen_string_literal: true",
		"",
		"# Autogenerated Rails controller scaffold.",
		"class ApplicationController < ActionController::Base",
		"  protect_from_forgery with: :exception",
		"",
		"  # Decoy identifiers that shape-only scanners over-flag:",
		"  SECRET_TOKEN = \"\"",
		"  API_KEY = ENV.fetch(\"API_KEY\", \"\")",
		"  before_action :authenticate_user!",
		"end",
		"",
	}
	lv := []string{"index", "show", "create", "update", "destroy", "search"}
	le := []string{"Gig", "Order", "Buyer", "Seller", "Review", "Payout"}
	return build(head, minLines, func(i int) []string {
		ctrl := le[(i/len(lv))%len(le)]
		act := lv[i%len(lv)]
		return []string{
			fmt.Sprintf("class %ssController%d < ApplicationController", ctrl, i),
			fmt.Sprintf("  def %s", act),
			fmt.Sprintf("    @records = %s.where(active: true).limit(50)", ctrl),
			"    respond_to do |format|",
			"      format.json { render json: { ok: true, data: @records } }",
			"      format.html",
			"    end",
			"  rescue StandardError => e",
			"    Rails.logger.error(\"handler failed: #{e.message}\")",
			"    head :internal_server_error",
			"  end",
			"end",
			"",
		}
	})
}

// CleanScala returns secret-free Scala service code of >= minLines lines.
func CleanScala(g *secrets.Gen, minLines int) string {
	head := []string{
		"package com.wix.platform.services",
		"",
		"import scala.concurrent.{ExecutionContext, Future}",
		"import com.wix.framework.http._",
		"",
		"// Decoy identifiers that shape-only scanners over-flag:",
		"object Config {",
		"  val secretToken: String = \"\"",
		"  val clientSecret: String = sys.env.getOrElse(\"CLIENT_SECRET\", \"\")",
		"}",
		"",
	}
	lv := []string{"list", "get", "create", "update", "delete", "render"}
	le := []string{"Site", "Editor", "Block", "Media", "Domain", "Premium"}
	return build(head, minLines, func(i int) []string {
		name := fmt.Sprintf("%s%s%d", lv[i%len(lv)], le[(i/len(lv))%len(le)], i)
		return []string{
			fmt.Sprintf("class %sService(implicit ec: ExecutionContext) {", name),
			"  def handle(req: Request): Future[Response] = Future {",
			"    val started = System.nanoTime()",
			fmt.Sprintf("    val payload = req.body.getOrElse(\"%s\")", name),
			"    Response(status = 200, body = s\"\"\"{\"ok\":true,\"handler\":\"$payload\"}\"\"\")",
			"  }",
			"}",
			"",
		}
	})
}

// CleanCSharp returns secret-free .NET controller code of >= minLines lines.
func CleanCSharp(g *secrets.Gen, minLines int) string {
	head := []string{
		"using System;",
		"using System.Threading.Tasks;",
		"using Microsoft.AspNetCore.Mvc;",
		"",
		"namespace Agoda.Booking.Api.Controllers",
		"{",
		"    // Decoy identifiers that shape-only scanners over-flag:",
		"    public static class Decoys",
		"    {",
		"        public const string SecretToken = \"\";",
		"        public static readonly string ApiKey = Environment.GetEnvironmentVariable(\"API_KEY\") ?? \"\";",
		"    }",
		"",
	}
	lv := []string{"List", "Get", "Create", "Update", "Delete", "Search"}
	le := []string{"Booking", "Hotel", "Flight", "Payment", "Ledger", "Refund"}
	return build(head, minLines, func(i int) []string {
		name := fmt.Sprintf("%s%s%d", lv[i%len(lv)], le[(i/len(lv))%len(le)], i)
		return []string{
			"    [ApiController]",
			fmt.Sprintf("    [Route(\"api/v2/%s\")]", strings.ToLower(name)),
			fmt.Sprintf("    public class %sController : ControllerBase", name),
			"    {",
			"        [HttpGet]",
			"        public async Task<IActionResult> Handle()",
			"        {",
			"            await Task.Yield();",
			fmt.Sprintf("            return Ok(new { ok = true, handler = \"%s\" });", name),
			"        }",
			"    }",
			"",
		}
	})
}

// ===========================================================================
// Dependency lockfiles — every line carries a high-entropy hash (generic-key FP).
// ===========================================================================

var goMods = []string{
	"github.com/gin-gonic/gin", "github.com/stretchr/testify", "golang.org/x/crypto",
	"google.golang.org/grpc", "github.com/spf13/cobra", "go.uber.org/zap", "github.com/lib/pq",
	"github.com/aws/aws-sdk-go-v2", "github.com/prometheus/client_golang", "github.com/google/uuid",
	"github.com/redis/go-redis/v9", "github.com/segmentio/kafka-go", "github.com/jackc/pgx/v5",
}

// GoSum returns a go.sum body of >= minLines lines (in-memory convenience).
func GoSum(g *secrets.Gen, minLines int) string {
	return toString(func(w io.Writer) error { return StreamGoSum(w, g, minLines) })
}

// StreamGoSum writes a go.sum (>= Scaled(minLines) lines) straight to w. Every
// line carries a high-entropy hash → the generic-key false-positive storm.
func StreamGoSum(w io.Writer, g *secrets.Gen, minLines int) error {
	minLines = Scaled(minLines)
	for i := 0; i < minLines; i += 2 {
		m := fmt.Sprintf("%s/v%d", goMods[i%len(goMods)], (i%6)+2)
		ver := fmt.Sprintf("v%d.%d.%d", g.Intn(6), g.Intn(20), g.Intn(40))
		fmt.Fprintf(w, "%s %s h1:%s=\n", m, ver, g.B64(42))
		fmt.Fprintf(w, "%s %s/go.mod h1:%s=\n", m, ver, g.B64(42))
	}
	return nil
}

var npmPkgs = []string{
	"lodash", "react", "express", "axios", "chalk", "commander", "debug", "glob",
	"semver", "yargs", "uuid", "ws", "dotenv", "jest", "eslint", "webpack", "rxjs", "redux", "zod", "vite",
}

// YarnLock returns a yarn.lock body of >= minLines lines (in-memory convenience).
func YarnLock(g *secrets.Gen, minLines int) string {
	return toString(func(w io.Writer) error { return StreamYarnLock(w, g, minLines) })
}

// StreamYarnLock writes a yarn.lock (>= Scaled(minLines) lines) to w.
func StreamYarnLock(w io.Writer, g *secrets.Gen, minLines int) error {
	minLines = Scaled(minLines)
	io.WriteString(w, "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT DIRECTLY.\n# yarn lockfile v1\n\n")
	for line := 3; line < minLines; line += 7 {
		i := line
		name := npmPkgs[i%len(npmPkgs)]
		ver := fmt.Sprintf("%d.%d.%d", g.Intn(20), g.Intn(30), g.Intn(40))
		fmt.Fprintf(w, "%s@^%s:\n", name, ver)
		fmt.Fprintf(w, "  version \"%s\"\n", ver)
		fmt.Fprintf(w, "  resolved \"https://registry.yarnpkg.com/%s/-/%s-%s.tgz#%s\"\n", name, name, ver, g.Hex(40))
		fmt.Fprintf(w, "  integrity sha512-%s==\n", g.B64(86))
		io.WriteString(w, "  dependencies:\n")
		fmt.Fprintf(w, "    %s \"^%d.%d.%d\"\n", npmPkgs[(i+1)%len(npmPkgs)], g.Intn(10), g.Intn(20), g.Intn(30))
		io.WriteString(w, "\n")
	}
	return nil
}

// PackageLock returns a package-lock.json body of >= minLines lines.
func PackageLock(g *secrets.Gen, minLines int) string {
	return toString(func(w io.Writer) error { return StreamPackageLock(w, g, minLines) })
}

// StreamPackageLock writes a package-lock.json (>= Scaled(minLines) lines) to w,
// emitting one package object per ~5 lines without buffering the whole document.
func StreamPackageLock(w io.Writer, g *secrets.Gen, minLines int) error {
	minLines = Scaled(minLines)
	n := minLines / 5
	if n < 1 {
		n = 1
	}
	io.WriteString(w, "{\n  \"name\": \"service\",\n  \"version\": \"1.0.0\",\n  \"lockfileVersion\": 3,\n  \"requires\": true,\n  \"packages\": {\n")
	for i := 0; i < n; i++ {
		name := fmt.Sprintf("%s-%d", npmPkgs[i%len(npmPkgs)], i)
		sep := ",\n"
		if i == n-1 {
			sep = "\n"
		}
		fmt.Fprintf(w, "    \"node_modules/%s\": {\n      \"version\": \"%d.%d.%d\",\n      \"resolved\": \"https://registry.npmjs.org/%s/-/%s.tgz\",\n      \"integrity\": \"sha512-%s==\"\n    }%s",
			name, g.Intn(20), g.Intn(30), g.Intn(40), name, name, g.B64(86), sep)
	}
	io.WriteString(w, "  }\n}\n")
	return nil
}

// ===========================================================================
// Access / proxy logs — 16-digit txn ids fire card-shaped FPs on every line.
// ===========================================================================

// LogOptions controls log generation and optional secret planting.
type LogOptions struct {
	MinLines int
	// PlantLine, when >= 0, appends a real-shaped secret to the line at that index.
	PlantLine int
	// Plant supplies the secret fragment to append (e.g. "stripe_key="+g.StripeLive()).
	Plant string
	Service string
}

// NginxLog returns an Nginx access log of >= opts.MinLines lines (in-memory).
func NginxLog(g *secrets.Gen, opts LogOptions) string {
	return toString(func(w io.Writer) error { return StreamNginxLog(w, g, opts) })
}

// StreamNginxLog writes an Nginx access log of >= Scaled(opts.MinLines) lines to
// w. Every line carries a 16-digit txn id (card-shaped FP). When opts.PlantLine
// >= 0 the opts.Plant fragment is buried on that line. PlantLine is interpreted
// against the UNSCALED index space so a plant at line N lands at N regardless of
// Scale.
func StreamNginxLog(w io.Writer, g *secrets.Gen, opts LogOptions) error {
	methods := []string{"GET", "POST", "PUT", "DELETE", "PATCH"}
	routes := []string{"/v2/bookings", "/v2/properties", "/v2/payments", "/assets/app.js", "/healthz", "/metrics", "/v2/quotes", "/api/kyc"}
	agents := []string{"Mozilla/5.0 (X11; Linux x86_64)", "okhttp/4.12", "curl/8.4.0", "Go-http-client/2.0", "python-requests/2.31"}
	codes := []string{"200", "201", "204", "301", "400", "401", "404", "429", "500", "502"}
	lines := Scaled(opts.MinLines)
	for i := 0; i < lines; i++ {
		fmt.Fprintf(w, "%s - - [%02d/Jun/2026:%02d:%02d:%02d +0000] \"%s %s HTTP/1.1\" %s %d txn_id=%s req_id=%s \"%s\"",
			g.IPv4(), 1+(i%28), i%24, i%60, (i*7)%60,
			g.Pick(methods), g.Pick(routes), g.Pick(codes), g.Intn(9000)+100,
			g.TxnID(), g.UUID(), g.Pick(agents))
		if i == opts.PlantLine && opts.Plant != "" {
			io.WriteString(w, " note="+opts.Plant)
		}
		io.WriteString(w, "\n")
	}
	return nil
}

// ===========================================================================
// Small infra docs
// ===========================================================================

// ReadmeMd returns a short service README.
func ReadmeMd(g *secrets.Gen, svc string) string {
	b := []string{"# " + svc, "", "Internal microservice. Autogenerated scaffold.", "", "## Endpoints", ""}
	for i := 0; i < 10+g.Intn(10); i++ {
		b = append(b, fmt.Sprintf("- `POST /v2/op/%d` — standard operation %d", i, i))
	}
	b = append(b, "", "## Ops", "", "Contact devops@example.com for access. Secrets live in Vault, never in-repo.")
	return strings.Join(b, "\n") + "\n"
}

// Dockerfile returns a minimal multi-stage Dockerfile.
func Dockerfile(g *secrets.Gen, base string) string {
	return strings.Join([]string{
		"FROM " + base, "WORKDIR /app", "COPY . .",
		fmt.Sprintf("ENV BUILD_REV=%d", g.Intn(99999)),
		"RUN make build", "EXPOSE 8443", "USER 1000", "ENTRYPOINT [\"/app/server\"]",
	}, "\n") + "\n"
}

// ===========================================================================
// Streaming big-file producers — the ~100MB+ scale drivers. Each writes line by
// line to an io.Writer (no whole-file buffering) and scales its volume by Scale.
// ===========================================================================

// toString drains a streaming producer into a string for the in-memory callers.
func toString(stream func(io.Writer) error) string {
	var sb strings.Builder
	_ = stream(&sb)
	return sb.String()
}

// PlantLog optionally buries a secret fragment on a specific (unscaled) line.
type PlantLog struct {
	MinLines  int
	PlantLine int    // < 0 to plant nothing
	Plant     string // the line content injected at PlantLine
}

// StreamAuditLog writes a CloudWatch/EKS-style audit log as JSON lines. Every
// line is a secret-free Kubernetes audit event — high volume, structurally
// busy, and full of UUIDs/ARNs that keep entropy scanners chattering.
func StreamAuditLog(w io.Writer, g *secrets.Gen, minLines int) error {
	verbs := []string{"get", "list", "watch", "create", "update", "patch", "delete"}
	resources := []string{"pods", "services", "deployments", "secrets", "configmaps", "nodes", "events", "ingresses"}
	namespaces := []string{"auth", "billing", "routing", "observability", "kube-system", "default"}
	users := []string{"system:serviceaccount:kube-system:deployment-controller", "arn:aws:iam::123456789012:role/eks-admin", "system:node:ip-10-40-12-8", "kubelet"}
	lines := Scaled(minLines)
	for i := 0; i < lines; i++ {
		fmt.Fprintf(w,
			"{\"kind\":\"Event\",\"apiVersion\":\"audit.k8s.io/v1\",\"level\":\"RequestResponse\",\"auditID\":\"%s\",\"stage\":\"ResponseComplete\",\"requestURI\":\"/api/v1/namespaces/%s/%s\",\"verb\":\"%s\",\"user\":{\"username\":\"%s\"},\"sourceIPs\":[\"%s\"],\"responseStatus\":{\"code\":%s},\"requestReceivedTimestamp\":\"2026-06-%02dT%02d:%02d:%02d.%03dZ\"}\n",
			g.UUID(), g.Pick(namespaces), g.Pick(resources), g.Pick(verbs), g.Pick(users), g.IPv4(),
			g.Pick([]string{"200", "201", "403", "404", "409"}),
			1+(i%28), i%24, i%60, (i*7)%60, g.Intn(1000))
	}
	return nil
}

// StreamJSONLog writes structured application JSON logs. Every line carries a
// 16-digit txn_id that card-shaped regexes mistake for a PAN (FP noise).
func StreamJSONLog(w io.Writer, g *secrets.Gen, svc string, minLines int) error {
	levels := []string{"INFO", "DEBUG", "WARN", "ERROR"}
	msgs := []string{"authorized payment", "captured funds", "settled ledger entry", "refund processed", "3ds challenge issued", "fraud score computed", "webhook dispatched"}
	lines := Scaled(minLines)
	for i := 0; i < lines; i++ {
		fmt.Fprintf(w,
			"{\"ts\":\"2026-06-%02dT%02d:%02d:%02d.%03dZ\",\"level\":\"%s\",\"service\":\"%s\",\"trace_id\":\"%s\",\"txn_id\":\"%s\",\"amount_cents\":%d,\"currency\":\"%s\",\"msg\":\"%s\"}\n",
			1+(i%28), i%24, i%60, (i*7)%60, g.Intn(1000), levels[i%len(levels)], svc,
			g.UUID(), g.TxnID(), g.Intn(500000)+100, g.Pick([]string{"USD", "THB", "SGD", "EUR"}), g.Pick(msgs))
	}
	return nil
}

// StreamCIJobLog writes a GitHub-Actions-style CI job log. When p.PlantLine >= 0
// it injects p.Plant (e.g. an `export AWS_SECRET_ACCESS_KEY=…` env dump) at that
// line — the classic "secret printed into the build log" leak.
func StreamCIJobLog(w io.Writer, g *secrets.Gen, p PlantLog) error {
	steps := []string{
		"Set up job", "Checkout", "Set up Ruby", "Install dependencies", "Run linters",
		"Run tests", "Build image", "Push to ECR", "Configure kubeconfig", "Deploy to cluster",
		"Run smoke tests", "Notify Slack", "Post Checkout", "Complete job",
	}
	lines := Scaled(p.MinLines)
	for i := 0; i < lines; i++ {
		if i == p.PlantLine && p.Plant != "" {
			fmt.Fprintf(w, "2026-06-19T%02d:%02d:%02d.%07dZ %s\n", i%24, i%60, (i*7)%60, g.Intn(9999999), p.Plant)
			continue
		}
		step := steps[(i/40)%len(steps)]
		fmt.Fprintf(w, "2026-06-19T%02d:%02d:%02d.%07dZ ##[group]%s | line %d | rev %s | status=ok elapsed=%dms\n",
			i%24, i%60, (i*7)%60, g.Intn(9999999), step, i, g.Hex(7), g.Intn(5000))
	}
	return nil
}

// StreamAirflowTaskLog writes an Airflow task-instance log. When p.PlantLine >= 0
// it injects a Python traceback line whose exception message echoes a Connection
// URI (p.Plant) with an embedded password — the airflow-task-log conn-uri leak.
func StreamAirflowTaskLog(w io.Writer, g *secrets.Gen, p PlantLog) error {
	files := []string{"taskinstance.py", "baseoperator.py", "python.py", "s3.py", "snowflake.py", "dagrun.py"}
	infos := []string{
		"Executing <Task(PythonOperator)> on 2026-06-20",
		"Exporting env vars to subprocess",
		"Dependencies all met for dep_context",
		"Marking task as SUCCESS",
		"Pushing xcom rows=%d", "Reading partition s3://insurify-quote-exports/dt=2026-06-20",
	}
	lines := Scaled(p.MinLines)
	for i := 0; i < lines; i++ {
		if i == p.PlantLine && p.Plant != "" {
			fmt.Fprintf(w, "[2026-06-20T%02d:%02d:%02d.%03d+0000] {taskinstance.py:1956} ERROR - Task failed with exception\n", i%24, i%60, (i*7)%60, g.Intn(1000))
			io.WriteString(w, "Traceback (most recent call last):\n")
			io.WriteString(w, "  File \"/opt/airflow/dags/secure_pipeline.py\", line 312, in _copy_into_snowflake\n")
			io.WriteString(w, "    hook = BaseHook.get_connection(conn_id)\n")
			io.WriteString(w, "  File \"/usr/lib/python3.11/site-packages/airflow/hooks/base.py\", line 73, in get_connection\n")
			fmt.Fprintf(w, "airflow.exceptions.AirflowException: could not parse connection uri %s\n", p.Plant)
			continue
		}
		msg := infos[i%len(infos)]
		if strings.Contains(msg, "%d") {
			msg = fmt.Sprintf(msg, g.Intn(9000))
		}
		fmt.Fprintf(w, "[2026-06-20T%02d:%02d:%02d.%03d+0000] {%s:%d} INFO - %s\n",
			i%24, i%60, (i*7)%60, g.Intn(1000), files[i%len(files)], 100+g.Intn(1900), msg)
	}
	return nil
}

// StreamSQLDump writes a pg_dump-style logical backup. Each INSERT row carries a
// Luhn-valid PAN and a synthetic SSN — PII in a SQL-dump format (not CSV/JSON)
// that structural matchers expecting tabular files miss. Benign FP noise.
func StreamSQLDump(w io.Writer, g *secrets.Gen, table string, rows int) error {
	io.WriteString(w, "--\n-- PostgreSQL database dump\n--\n\n")
	io.WriteString(w, "SET statement_timeout = 0;\nSET client_encoding = 'UTF8';\nSET standard_conforming_strings = on;\n\n")
	fmt.Fprintf(w, "CREATE TABLE public.%s (\n    id bigint NOT NULL,\n    holder text,\n    ssn character varying(11),\n    card_pan character varying(19),\n    amount numeric(12,2),\n    created_at timestamp with time zone\n);\n\n", table)
	fmt.Fprintf(w, "COPY public.%s (id, holder, ssn, card_pan, amount, created_at) FROM stdin;\n", table)
	n := Scaled(rows)
	for i := 0; i < n; i++ {
		fmt.Fprintf(w, "%d\t%s %s\t%s\t%s\t%d.%02d\t2026-06-%02d %02d:%02d:%02d+00\n",
			1000000+i, strings.Title(g.Lower(5)), strings.Title(g.Lower(7)),
			g.RandSSN(), g.LuhnCard(), g.Intn(9000)+10, g.Intn(100),
			1+(i%28), i%24, i%60, (i*7)%60)
	}
	io.WriteString(w, "\\.\n\n--\n-- PostgreSQL database dump complete\n--\n")
	return nil
}

// StreamNDJSON writes a data-lake event stream as newline-delimited JSON. Every
// record is secret-free but seeded with UUIDs that get mistaken for tokens (FP).
func StreamNDJSON(w io.Writer, g *secrets.Gen, minLines int) error {
	events := []string{"quote.created", "quote.viewed", "policy.bound", "premium.computed", "claim.opened", "payment.captured"}
	lines := Scaled(minLines)
	for i := 0; i < lines; i++ {
		fmt.Fprintf(w,
			"{\"event_id\":\"%s\",\"session_token\":\"%s\",\"type\":\"%s\",\"user_ref\":\"%s\",\"ts\":%d,\"amount\":%d.%02d}\n",
			g.UUID(), g.UUID(), events[i%len(events)], g.UUID(),
			1718000000+i, g.Intn(5000)+100, g.Intn(100))
	}
	return nil
}

// StreamCSV writes a header plus Scaled(rows) lines produced by row(i). Generic
// streaming CSV helper for the synthetic-PII export dumps.
func StreamCSV(w io.Writer, header string, rows int, row func(i int) string) error {
	io.WriteString(w, header+"\n")
	n := Scaled(rows)
	for i := 0; i < n; i++ {
		io.WriteString(w, row(i)+"\n")
	}
	return nil
}

// TelemetryPEM returns a PEM-armored block whose base64 body decodes to a benign
// metrics blob. A naive `-----BEGIN …-----` regex flags it as a private key, but
// it leaks nothing — the semantic false positive that only a context engine can
// clear.
func TelemetryPEM(g *secrets.Gen) string {
	var raw strings.Builder
	for i := 0; i < 24; i++ {
		fmt.Fprintf(&raw, "metric=%s host=ip-10-40-%d-%d cpu=%d.%d mem=%d.%d net_in=%d net_out=%d;",
			g.Pick([]string{"cpu.idle", "mem.used", "net.rx", "disk.io", "lat.p99"}),
			g.Intn(255), g.Intn(255), g.Intn(100), g.Intn(10), g.Intn(64), g.Intn(10),
			g.Intn(100000), g.Intn(100000))
	}
	enc := base64.StdEncoding.EncodeToString([]byte(raw.String()))
	var b strings.Builder
	b.WriteString("-----BEGIN OPENTELEMETRY METRIC STREAM-----\n")
	for i := 0; i < len(enc); i += 64 {
		end := i + 64
		if end > len(enc) {
			end = len(enc)
		}
		b.WriteString(enc[i:end] + "\n")
	}
	b.WriteString("-----END OPENTELEMETRY METRIC STREAM-----\n")
	return b.String()
}

// FixedWidthPII returns a pipe-delimited fixed-width PII export — synthetic SSNs
// and DOBs in a non-standard columnar format that rigid CSV/JSON matchers skip.
func FixedWidthPII(g *secrets.Gen, rows int) string {
	var b strings.Builder
	b.WriteString("# KYC fixed-width export | id(7) | surname(12) | given(12) | ssn(11) | dob(10) | country(2)\n")
	n := Scaled(rows)
	for i := 0; i < n; i++ {
		fmt.Fprintf(&b, "%07d|%-12s|%-12s|%s|%04d-%02d-%02d|%s\n",
			i, strings.ToUpper(g.Lower(g.IntRange(4, 11))), strings.Title(g.Lower(g.IntRange(3, 10))),
			g.RandSSN(), g.IntRange(1955, 2004), g.IntRange(1, 12), g.IntRange(1, 28),
			g.Pick([]string{"US", "IN", "GB", "PK", "PH", "NG", "BR", "DE", "IL"}))
	}
	return b.String()
}
